//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankCardProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankCardProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla oluşturuldu..
        /// </summary>
        public static string CRUD1000 {
            get {
                return ResourceManager.GetString("CRUD1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt oluşturulurken beklenmedik bir hata oluştu..
        /// </summary>
        public static string CRUD1001 {
            get {
                return ResourceManager.GetString("CRUD1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerekli alanlar eksik; kayıt oluşturulamadı..
        /// </summary>
        public static string CRUD1002 {
            get {
                return ResourceManager.GetString("CRUD1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı kayıt zaten mevcut..
        /// </summary>
        public static string CRUD1003 {
            get {
                return ResourceManager.GetString("CRUD1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kart numarası zaten kayıtlı..
        /// </summary>
        public static string CRUD1004 {
            get {
                return ResourceManager.GetString("CRUD1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla getirildi..
        /// </summary>
        public static string CRUD2000 {
            get {
                return ResourceManager.GetString("CRUD2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstenen kayıt bulunamadı..
        /// </summary>
        public static string CRUD2001 {
            get {
                return ResourceManager.GetString("CRUD2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt getirilirken hata oluştu..
        /// </summary>
        public static string CRUD2002 {
            get {
                return ResourceManager.GetString("CRUD2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri okunamadı, lütfen tekrar deneyin..
        /// </summary>
        public static string CRUD2003 {
            get {
                return ResourceManager.GetString("CRUD2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt listesi boş..
        /// </summary>
        public static string CRUD2004 {
            get {
                return ResourceManager.GetString("CRUD2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla güncellendi..
        /// </summary>
        public static string CRUD3000 {
            get {
                return ResourceManager.GetString("CRUD3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellenecek kayıt bulunamadı..
        /// </summary>
        public static string CRUD3001 {
            get {
                return ResourceManager.GetString("CRUD3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen veri geçersiz; güncelleme yapılamadı..
        /// </summary>
        public static string CRUD3002 {
            get {
                return ResourceManager.GetString("CRUD3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme sırasında beklenmedik bir hata oluştu..
        /// </summary>
        public static string CRUD3003 {
            get {
                return ResourceManager.GetString("CRUD3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string CRUD4000 {
            get {
                return ResourceManager.GetString("CRUD4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinecek kayıt bulunamadı..
        /// </summary>
        public static string CRUD4001 {
            get {
                return ResourceManager.GetString("CRUD4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi sırasında hata oluştu..
        /// </summary>
        public static string CRUD4002 {
            get {
                return ResourceManager.GetString("CRUD4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kart zaten pasif durumda..
        /// </summary>
        public static string CRUD4003 {
            get {
                return ResourceManager.GetString("CRUD4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı doğrulaması başarısız..
        /// </summary>
        public static string ERR1001 {
            get {
                return ResourceManager.GetString("ERR1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkisiz erişim..
        /// </summary>
        public static string ERR1002 {
            get {
                return ResourceManager.GetString("ERR1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerekli parametre eksik..
        /// </summary>
        public static string ERR1003 {
            get {
                return ResourceManager.GetString("ERR1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz parametre değeri..
        /// </summary>
        public static string ERR1004 {
            get {
                return ResourceManager.GetString("ERR1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping işlemi sırasında beklenmedik bir hata oluştu..
        /// </summary>
        public static string ERR1005 {
            get {
                return ResourceManager.GetString("ERR1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı..
        /// </summary>
        public static string ERR1006 {
            get {
                return ResourceManager.GetString("ERR1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu hatası oluştu..
        /// </summary>
        public static string ERR1007 {
            get {
                return ResourceManager.GetString("ERR1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı bağlantısı başarısız oldu..
        /// </summary>
        public static string ERR1008 {
            get {
                return ResourceManager.GetString("ERR1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem zaman aşımına uğradı..
        /// </summary>
        public static string ERR1009 {
            get {
                return ResourceManager.GetString("ERR1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka kartı listesi boş..
        /// </summary>
        public static string ERR1010 {
            get {
                return ResourceManager.GetString("ERR1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre yanlış..
        /// </summary>
        public static string ERR1011 {
            get {
                return ResourceManager.GetString("ERR1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erişim reddedildi..
        /// </summary>
        public static string ERR1012 {
            get {
                return ResourceManager.GetString("ERR1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi sırasında hata meydana geldi..
        /// </summary>
        public static string ERR1013 {
            get {
                return ResourceManager.GetString("ERR1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme sırasında bir hata oluştu..
        /// </summary>
        public static string ERR1014 {
            get {
                return ResourceManager.GetString("ERR1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz kart ID değeri. ID pozitif bir sayı olmalıdır..
        /// </summary>
        public static string ERR1015 {
            get {
                return ResourceManager.GetString("ERR1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt zaten mevcut..
        /// </summary>
        public static string ERR1016 {
            get {
                return ResourceManager.GetString("ERR1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt zaten mevcut..
        /// </summary>
        public static string ERR1017 {
            get {
                return ResourceManager.GetString("ERR1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt zaten mevcut..
        /// </summary>
        public static string ERR1018 {
            get {
                return ResourceManager.GetString("ERR1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt zaten mevcut..
        /// </summary>
        public static string ERR1019 {
            get {
                return ResourceManager.GetString("ERR1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt zaten mevcut..
        /// </summary>
        public static string ERR1020 {
            get {
                return ResourceManager.GetString("ERR1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt zaten mevcut..
        /// </summary>
        public static string ERR1021 {
            get {
                return ResourceManager.GetString("ERR1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt zaten mevcut..
        /// </summary>
        public static string ERR1022 {
            get {
                return ResourceManager.GetString("ERR1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarıyla tamamlandı..
        /// </summary>
        public static string INFO5000 {
            get {
                return ResourceManager.GetString("INFO5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem devam ediyor, lütfen bekleyiniz..
        /// </summary>
        public static string INFO5001 {
            get {
                return ResourceManager.GetString("INFO5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri güncellendi, lütfen sayfayı yenileyiniz..
        /// </summary>
        public static string INFO5002 {
            get {
                return ResourceManager.GetString("INFO5002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı: Kayıt üzerinde başka işlemler devam ediyor..
        /// </summary>
        public static string WARN6000 {
            get {
                return ResourceManager.GetString("WARN6000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat: Veri kilitli, işlem yapılamıyor..
        /// </summary>
        public static string WARN6001 {
            get {
                return ResourceManager.GetString("WARN6001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı: İşlem tamamlanmadan önce lütfen kontrol ediniz..
        /// </summary>
        public static string WARN6002 {
            get {
                return ResourceManager.GetString("WARN6002", resourceCulture);
            }
        }
    }
}
